export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const PROJECTS_DATA = 'PROJECTS_DATA';
export const NEWS_DATA = 'NEWS_DATA';
export const PROJECT_DATA = 'PROJECT_DATA';
export const SUCCESS_DATA = 'SUCCESS_DATA';
export const SUCCESS_USERINFO = 'SUCCESS_USERINFO';